### ISSUE TITLE
Automatic publish of API to major catalogues

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/docs#102]
# What is the problem?

We are not using the free publicity of API catalogs to let every developer to know about our APIs and opportunities. 

# What do you expect to see / happen? 
Design and implement automatic push of API spec and details to selected API catalogs. The catalog must provide API which can be used to add and update own APIs in catalog. 

This should be part of the automatic rebuild of API Docs. 

Value is that our APIs can be found from various sources. At the same time our platform is getting visibility and attention. From the catalogs we can get more traffic to developer portal and possibly get new developers onboard. 

- [ ] Define the wanted catalogues
- [ ] Check if they have API and how the adding and updating can be done with API
- [ ] Build as part of the build.py logic in API Docs

**Comment by kyyberi** [comment]
Move to JIRA
